version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://user:password@db:5432/championship
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["gunicorn", "--bind", "0.0.0.0:9000", "main:app"]
    ports:
      - "${PORT:-9000}:9000"
    
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=championship
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d championship"]
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring:
    build: 
      context: ./monitoring
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MONITORING_INTERVAL=300000
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  proxy:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
    ports:
      - "4030:80"
    depends_on:
      - web
      - prometheus
      - grafana

volumes:
  postgres_data:
