global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:9000']
    scrape_interval: 5s

  - job_name: 'nginx'
    static_configs:
      - targets: ['proxy:80']
    metrics_path: '/nginx_status'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']
    scrape_interval: 10s