global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:9000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(attendance_count_total|user_streak_days|user_points|response_time_seconds.*|audit_actions_total|arrival_time_hours.*)$'
        action: keep
  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'nginx'
    static_configs:
      - targets: ['proxy:80']