global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:9000']
  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']